### ISSUE TITLE
Connect Antennas with Jellyfin Server ?

### ISSUE THREAD

**Issue by dnmnhat** [jfarseneau/antennas#101]
I'm using Jellyfin, and I also build Antennas to connect to Jellyfin, but when I setup, Jellyfin can't connect to Antennas, even though I try manual setup it still fails.
I don't know if Antennas supports Jellyfin? or does it only support Plex???

**Comment by jfarseneau** [comment]
I've never actually tested it on Jellyfin, and I was surprised that it was listed in Jellyfin's plugins! If it supports HDHomeRun, then it should work, but that's more of a lucky coincidence.

**Comment by dnmnhat** [comment]
with Plex and Emby I have no problem connecting to Antennas.  But with Jellyfin I can't connect or find Antennas.  Yes, I will use Emby or Plex.  If you have Jellyfin support in the future, that's great

**Comment by justinthegeek** [comment]
@dnmnhat Make sure you add the Antennas port to Jellyfin. I'm able to get Jellyfin to see Antennas, but I'm dealing with the channel count undefind issue at the moment.

**Comment by dnmnhat** [comment]
successful connection with manual setting IP:PORT ( not http )

**Comment by anthonylavado** [comment]
A Jellyfin team lead here. You can technically use Antennas to connect TVHeadend into Jellyfin, as we do have HDHomeRun support. I used this for a few years, until I learned that TVHeadend gives you an M3U as well, and you can just use that for Jellyfin (so there's no need to run Antennas).

That said, if anyone has any questions, just let me know.

**Comment by jfarseneau** [comment]
Thanks @anthonylavado for responding! Definitely agree that it's best to use the built-in Jellyfin features.

**Comment by jadero** [comment]
For anyone that ends up looking here. The correct way to add tvheadend to jellyfin was posted [here](https://tvheadend.org/d/8680-how-to-export-tvheadend-channels-to-m3u-and-a-xmltv-guide-for-jellyfin):

> Under "Live TV" add a M3U Tuner. In "File or URL" put:
>
>http://urtvheadendip:9981/playlist/channels.m3u
>
>For TV Guide you can put:
>
>http://urtvheadendip:9981/xmltv/channels
