### ISSUE TITLE
Cannot tune channel in plex

### ISSUE THREAD

**Issue by hexonMD** [jfarseneau/antennas#26]
I'm able to install and link to tvheadend without any issue. All my channels show up but it won't actually play any of them

**Comment by mutluerol** [comment]
HDHomerun (Antennas)
127.0.0.1:5004
Device not found. Ensure your device is powered on and connected to your network.

**Comment by mutluerol** [comment]
Jun 22 04:45:25 arch PlexMediaServer[9124]: DVR:Schedule: Couldn't schedule recording (tuned channel: 0)
Jun 22 04:45:25 arch PlexMediaServer[9124]: DVR:Subscription: Rolling media grab failed to start.

**Comment by DavidSpek** [comment]
I also had this issue, or one related to it. First, I found out I had forgotten to set up an anonymous user in Tvheadend, which made me feel a bit stupid. After setting that up I was disappointed when plex stil would not tune a channel, however it start syncing the guide properly. Then I thought changing the DVR transcoder setting in Plex from highest to original format. After changing the transcoder setting to original format everything, including encrypted channels, started streaming correctly. Hopefully this helps.

**Comment by martijndierckx** [comment]
Similar issue here.
Recording works flawlessly. However, streaming live only works for a handful of channels.
Most channels immediately show: "Unable to tune channel".

I have tried the docker variant, and the local nodejs variant. Both have the same problems.
Changing the quality to "original" doesn't work either.

What can I provide you guys with to investigate this issue?

**Comment by toleeck** [comment]
I encountered the same problem. No channels from the tvh are launched in the plex. An error occurs when you can not tune in to a channel.
the log in tvh produces
> 2018-08-14 07:01:41.985 profile: unable to select a working profile (asked '(null)' alt 'channel')
> 2018-08-14 07:01:41.985 http: 192.168.88.245: HTTP/1.1 GET (1) /stream/channel -- 503

**Comment by fredamn76** [comment]
any fix for this yet?

**Comment by TheJF** [comment]
Not yet; I haven't really invested any time in developing Antennas for a while unfortunately.

**Comment by kanet0x** [comment]
I have the same issue. 
Device not found. Ensure your device is powered on and connected to your network.

**Comment by razulian** [comment]
I can validate that tenfire's commit fixes the tuner issue. I'm using Tvheadend 4.3 and the latest version of Plex.

**Comment by ledfloyd1984** [comment]
@razulian Could you share your binaries? I have absolutely no clue how to build the source for this.

**Comment by jfarseneau** [comment]
Fixed through https://github.com/jfarseneau/antennas/pull/39 . Sorry for neglecting this software everyone!
