### ISSUE TITLE
Incorrect Number Of Tuners?

### ISSUE THREAD

**Issue by Migz93** [jfarseneau/antennas#27]
I have 2 physical tuners plumbed into tvheadend.
My antennas is configured with "TUNER_COUNT" = 2 but once antennas is added to plex i'm seeing 50 tuners which is a bit of a pain as i don't get recording schedule conflicts as my plex server thinks theres loads of tuners.
If i set the TUNER_COUNT to 1 then i get 49 tuners, if i set it to 3 i get 51 tuners.

**Comment by ideasman69** [comment]
Yeah I'm seeing the same thing!

![vmware_2018-11-09_07-53-40](https://user-images.githubusercontent.com/19260137/48226825-c87d9980-e3f4-11e8-9829-5928898242af.png)

Awesome job though @TheJF - this is a great little app

**Comment by DasPflanze** [comment]
Yes, I'm having the same problem...
Did someone find a workaround?

**Comment by DasPflanze** [comment]
So I found one myself. Using the config.yml instead of environment variables I've got now the right amount of tuners.

**Comment by bennydiamond** [comment]
2 in ASCII translate to a numerical value of 50 (base10).
Clearly, value of TUNER_COUNT is cast from string to int. Try to write it with quotes:

> TUNER_COUNT="2"
