### ISSUE TITLE
Does the multiple tuners function work?

### ISSUE THREAD

**Issue by danielloader** [jfarseneau/antennas#29]
I've got 3 tuners showing in TVheadend and can get three simultaneous streams on VLC so I've tested the backend functionality - does antennas correctly pass this over to Plex?
I've tried with two plex clients and the second one never tunes to a channel if the first one is actively tuned in.

**Comment by jfarseneau** [comment]
There was a bug with environment variables not being parsed correctly in Antennas, but this should now be fixed. If you're still using the software, you can give a shot to the newest version and see if it works out correctly.

Thanks!
