### ISSUE TITLE
Password should not be displayed in Clear Text in WEBUI

### ISSUE THREAD

**Issue by thehaxxa** [jfarseneau/antennas#42]
Although you could run this software behind a reverse proxy and use a firewall to limit access, it would be nice if the passwords were not exposed directly in Cleartext!. (_even if the url contains the password_).

Its a pretty big security concern, and enables anyone on the network to access that TVHeadEnd user. 

Maybe just display IP Address, User and Port? Consider some additional security measures if possible?

**Comment by TheJF** [comment]
Fair point, fair point. It should be tightened up.

**Comment by jfarseneau** [comment]
Done! It no longer shows this in the frontend with the latest version. Thanks for bringing up the issue!
