### ISSUE TITLE
Tag and release new version and publish to npm

### ISSUE THREAD

**Issue by bachp** [jfarseneau/antennas#52]
It would be nice if antennas is available npmjs.org.
 
So installing it would be as easy as running: `npm install -g antennas`

**Comment by jfarseneau** [comment]
That's a good idea. If I can set aside some time for this repo, I'll get this setup.

**Comment by jfarseneau** [comment]
Done!

You can now go `npm install -g antennas` and use `antennas` to launch it, or you can also use `npx antennas` to run it directly from NPM.
