### ISSUE TITLE
No matter what options I try, it doesn't work

### ISSUE THREAD

**Issue by user897943** [jfarseneau/antennas#69]
I used this dockerized, no matter what I try, it doesn't work. I tried setting up the user a million ways, with and without password, I tweaked the environment variables too. It simply doesn't work. Fails to authenticate. Is this being maintained at all?

**Comment by patrickaoude** [comment]
I have the same issue, but I know the environment variables are set correctly (I see them set on the antennas page at x.x.x.x:5004).
If I click on the link for tvHeadend and open in a private tab it logs me in, so credentials are correct and the service is running.

**Comment by user897943** [comment]
Clearly not maintained, what a pity, such a useful application, I'd do it myself if I knew how to code.

**Comment by jfarseneau** [comment]
Well, it's only maintained as far as I sometimes poke at it whenever I feel up to it.

Sorry to hear it's not working out for your setup though. I'd say if you're willing to take another stab at it, try pulling the `latest`, and make sure that Tvheadend and Antennas can communicate.

There's a future where I'd like to cut out Tvheadend entirely, but as you've noticed, this project doesn't get a whole lot of love, so not sure when/if I'll get to that.

**Comment by user897943** [comment]
Unfortunately it doesn't work. I tried "tellytv" and it does work but it stops overnight for some reason, so I know other apps work meaning my tvheadend is configured correctly as I can even watch the channels. I'd prefer to use your app though because it can do multi-tuner.

Here's the message I get on Plex:
There was a problem getting the channels for your device
<img width="469" alt="plex" src="https://user-images.githubusercontent.com/5891221/163723841-a2719d10-b47f-4e7e-82a5-ce22435f6a0e.png">
There are active channels on TVH and as said above the other plex proxy app works "okay".

Here's what I can see in antennas:
<img width="383" alt="antennas" src="https://user-images.githubusercontent.com/5891221/163723879-f7b2eea4-4fe4-49de-a288-65c69ee64804.png">

Pity that the project doesn't see much love. I think it's very useful from a theoretical perspective just wish it worked for me in practice. I would like to be able to just pull data from my sat>ip server and pass to plex, be able to deactivate channels directly within the app so plex wouldn't have a bunch of redundant channels. And parsing xmltv then passing to plex also. But at least if the app worked as a proxy it would be cool. Not sure why it's not working.

**Comment by jfarseneau** [comment]
Hm, what do you get if you go to http://your_username:your_password@10.0.0.100:9981/api/channel/grid?start=0&limit=999999

Make sure to change `your_username` and `your_password` above to your Tvheadend username and password

**Comment by user897943** [comment]
This is what I get:

https://pastebin.com/PLwvd2vm

**Comment by jfarseneau** [comment]
Thanks! So seems like the error _may_ be something to do with basic auth vs digest auth.

Basically this error here:
```
TypeError: body.entries is not iterable
      at module.exports (/antennas/src/lineup.js:8:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /antennas/src/router.js:399:16
      at async logger (/antennas/node_modules/koa-logger/index.js:67:7)
```

Says that it can't find "entries", but in your link, it does return it. Antennas is not able to talk to Tvheadend properly. But it does connect to it, as seen in your screenshot. Which is weird.

It _could_ be something to do with that it's trying to connect using a different type of authentication. Tvheadend provides basic auth (which is the username:password@your_tvheadend_url) and digest auth where the username and password get sent differently. There was an update at some point that switched Tvheadend from basic auth to digest auth, and then Antennas was updated for that: https://github.com/jfarseneau/antennas/issues/18

I'd recommend trying this. Go to Tvheadend, in the Configuration tab, General tab, Base tab, switch the view level to Expert, and then there's going an option called HTTP Server Settings. In there we want Authentication type, and set it to "Both plain and digest"

![image](https://user-images.githubusercontent.com/999846/163730095-93239610-dc8e-433a-8a96-b83e27cb1363.png)

Hopefully that'll help?

**Comment by user897943** [comment]
Hey, thanks, I already changed the settings and played with all different kinds of combinations, sometimes I would get a 401 error which means authentication was broken but on plain and digest md5 i get error 500:

 'Nb             `KN~  NN~    vNY   ^bNNNI  |SQNNNB9~  ~NN     wN{  vNs    ~NN  `xQNNBGVNl `Y#NNNNG^ v4.1.1
📡 Antennas are deployed! Proxying from http://10.0.0.100:5004
🕵️‍  Broadcasting to SSDP for discovery...
  <-- GET /lineup.json
  xxx GET /lineup.json 500 34ms - <<<<<<<<<<<<<<<< NOT AUTHENTICATION ISSUE
  TypeError: body.entries is not iterable
      at module.exports (/antennas/src/lineup.js:8:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /antennas/src/router.js:399:16
      at async logger (/antennas/node_modules/koa-logger/index.js:67:7)
  <-- GET /discover.json
  --> GET /discover.json 200 3ms 388b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 1ms 77b

I am using HTS Tvheadend 4.3-2008~ge2ae8f4eb

**Comment by user897943** [comment]
One lineup.js
if you change from ```         URL: `${config.tvheadend_stream_url}/stream/channel/${channel.uuid}`,```
to ```        URL: `${config.tvheadend_stream_url}/stream/channelid/${channel.uuid}`,```
What do you think it would happen?
The reason I ask is because I did http://server:9981/playlist/channels
it downloaded the m3u with all the channels
When I play on VLC the url looks like this:
``` http://10.0.0.100:9981/stream/channelid/286592317?profile=pass ```

**Comment by user897943** [comment]
I tried running chvb/docker-tvhproxy:latest and it does list all the channels but when I try to play anything, plex says "source is unavailable" and does not play back the video. On the tvheadend logs:
```2022-04-18 17:56:07.412 subscription: 01E3: "HTTP" subscribing on channel "BBC One HD", weight: 300, adapter: "SAT>IP DVB-S Tuner #4 (10.0.0.119@UDP)", network: "Satellite", mux: "10847V", provider: "BSkyB", service: "BBC One HD", profile="pass", hostname="10.0.0.124", client="Lavf/58.65.101"```
So really not sure what is happening

**Comment by davmc123** [comment]
I've got the same issue with the latest docker version as @user897943 . I think this error has been introduced in the latest update though, as I had the docker version working with a previous image version. 

**Docker Error Codes**
```
TypeError: body.entries is not iterable
      at module.exports (/antennas/src/lineup.js:8:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /antennas/src/router.js:399:16
      at async logger (/antennas/node_modules/koa-logger/index.js:67:7)
```

I also tried to upgrade a working node version of antennas (**3.1.0**) on a Raspberry Pi 3B+ to the latest version (**4.1.1**) and had some similar errors with the latest version.

**Node Version Error Codes (Version 4.1.1)**
```
xxx GET /lineup.json 500 92ms -

Error: Request failed with status code 403
    at createError (/home/pi/Antennas-TVHProxy/AT_new/antennas/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/Antennas-TVHProxy/AT_new/antennas/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/Antennas-TVHProxy/AT_new/antennas/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)     
``` 

Both errors had the same effect where plex couldn't see any channels, with plex providing an error stating:
> There was a problem getting the channels for your device. 

I also tried downloading and running version **4.1.0** which worked correctly, so I think this issue is with a change in the newest version.

**Comment by SeraphimSerapis** [comment]
Same as above. Had to revert to 4.1.0 to get things to work again.

**Comment by jfarseneau** [comment]
Hm, okay, I'll see if I can push a build to fix this soon. Sorry about this folks

**Comment by jfarseneau** [comment]
New version out, let me know if that fixes it!

**Comment by SeraphimSerapis** [comment]
Working great here. Thanks for the quick fix!

**Comment by jfarseneau** [comment]
Awesome, glad to hear! Thanks for the update!

**Comment by davmc123** [comment]
Looks like that has fixed it for me too, Thanks.

**Comment by user897943** [comment]
My tvheadend was already set with both plain and digest
