### ISSUE TITLE
wrong Tuner Count detected in Plex

### ISSUE THREAD

**Issue by cholzer79** [jfarseneau/antennas#73]
TvHeadEnd runs on an Debian system
Installed antennas using the docker method.
Antennas Config setting shows "Tuner Count = 2" which is correct.
https://imgur.com/T1p0v6q

But plex thinks that I have 55 tuners!?
https://imgur.com/ky7JDiI

Tuning inside Plex fails with the error that the source is not available, TvHeadend does tune the channel though.

**update**
the docker is clearly out of date. 
I now tried the npx route. 
the number of tuners is correct and streaming works as well!

the Antennas documentation needs some work because it was not clear to me how to get Antennas running with npx (creation/location of config.yml) and how to auto-start it on boot (created a cron job for this now).

I figured it out eventually but the documentation makes the setup a lot harder than it has to be (if you are a noob like me).

**Comment by eloiseaa728** [comment]
Also have this issue.

**Comment by eloiseaa728** [comment]
For anyone looking to run their Antennas as a systemd service outside of docker, example of a service

`[Unit]
Description=Antennas
After=network.target (docker.service or tvheadend.service depending on if you are running tvheadend in docker or outside)

[Service]
Type=simple
User=<USER>
ExecStart=/usr/bin/node /dir/to/antennas/index.js --config /dir/to/antennas/config/config.yml
WorkingDirectory=/dir/to/antennas/
Restart=on-failure

[Install]
WantedBy=multi-user.target`

**Comment by jfarseneau** [comment]
Sorry about that, `latest` has been updated so if you'd like to go back to the Docker way using `latest` you can. Otherwise, `npx` is a good way to run it!
