### ISSUE TITLE
4.1 not tag latest in docker

### ISSUE THREAD

**Issue by rado0x54** [jfarseneau/antennas#75]
Just a note, that `latest` tag on [dockerhub](https://hub.docker.com/r/thejf/antennas/tags) does not point to `4.1`, the actual latest version. This could cause confusion because some fixes are not found in the default version (for me it was the credential forward in the lineup URL), but also the # of tuners.

**Comment by jfarseneau** [comment]
Ahh, good catch. Sorry about that! I'll fix that

**Comment by jfarseneau** [comment]
Fixed! Thanks for the report (and the suggested fix!)
