### ISSUE TITLE
Digest auth not working since version 4.1.1

### ISSUE THREAD

**Issue by yayitazale** [jfarseneau/antennas#85]
The update of the last week break the digest auth mode and I had to change it to "Both Plain and Digest" mode on TvHeadend. As I see in #18 this was implemented 2 years ago so something must be broken with the last update.

Thanks.

**Comment by Jimbob-B** [comment]
This seems to be an issue for me too with the tarball for v4.1.2. Digest auth fails with 401 and changing the setting to Basic and Digest in TVHeadend works.

I'm running antennas as a service using `node index.js` on Raspberry Pi 64 bit using node v17.9.0.

**Comment by jfarseneau** [comment]
@yayitazale @Jimbob-B Hmm, what kind of error are you getting? I have it on Digest on my side and it seems to work using 4.1.2, running `node index.js`

**Comment by Jimbob-B** [comment]
@jfarseneau  This is what I am seeing when TVHeadend is set to digest only for the service on Raspberry OS (aka Debian bullseye),

`May 01 11:33:38 myhostname node[68123]:   --> GET /images/Antennas-Logo.svg 200 2ms 3.78kb`
`May 01 11:33:38 myhostname node[68123]:   <-- GET /antennas_config.json`
`May 01 11:33:38 myhostname node[68123]:     Antennas failed to connect to Tvheadend!`
`May 01 11:33:38 myhostname node[68123]:     Check that:`
`May 01 11:33:38 myhostname node[68123]:       - Tvheadend is running.`
`May 01 11:33:38 myhostname node[68123]:       - Antennas is correctly pointing to Tvheadend, on >`
`May 01 11:33:38 myhostname node[68123]:       - That your username and login are correct.`
`May 01 11:33:38 myhostname node[68123]:     Here's a dump of the error:`
`May 01 11:33:38 myhostname node[68123]:     Error: Request failed with status code 401`
`May 01 11:33:38 myhostname node[68123]:   --> GET /antennas_config.json 200 6ms 591b`

The status web page then shows,
![Antennas error](https://user-images.githubusercontent.com/77790254/166143115-3e5fe5c7-6596-4f0f-8f58-a031f75cc174.jpg)

As soon as I flick it back to both basic and digest in the settings it then works correctly. I read the bug report that lead to the hotfix release first and thought I had made a config error but copying the config from my old working Antennas still shows the same issue (I think this was the tarball from the 1st January release).

**Comment by jfarseneau** [comment]
@Jimbob-B Thanks for the info! I may have a fix over here https://github.com/jfarseneau/antennas/pull/88 , I just want to make sure I don't once again break something else since uh, my track record isn't super here, but I can hopefully get this out soon.

Sorry again for the issue!

**Comment by rtm516** [comment]
I can confirm using #88 fixes the issue for me

**Comment by Jimbob-B** [comment]
Looks good to me too and thanks for fixing 👍 

This is the only way I have found that reliably lets me use Plex DVR with my Raspberry Pi and it's cheaper than trying to find a HDHomerun in the UK ... thank you

**Comment by jfarseneau** [comment]
@Jimbob-B Glad to hear it fixed it! :D Looks like the rest works well, so I'll push out a new official version. And thank you for the thanks (and for reporting the issue and testing it), it's very appreciated and I'm glad Antennas is helpful!
