### ISSUE TITLE
Change docker execution command from `npx .` to `npx --yes .` to prevent prompts on new container creation?

### ISSUE THREAD

**Issue by davmc123** [jfarseneau/antennas#86]
When I create a new docker container based on the antennas image, I get the following prompt/output:
```
Need to install the following packages:
  file:
```
To get the container to run, I need to attach to the container and send a 'y' to finish the setup.

Changing the execution command from `npx .` to `npx --yes .` seems to stop the prompt being required on startup. Maybe this could be added to the Dockerfile to make setup a bit smoother?

**Comment by jfarseneau** [comment]
Hmm, I don't get this error on Docker for some reason, but happy to add that in to help.
